import { IMAGES } from "./mock-data-images";

export const curatedProducts = 
[
  // ─── ALIMENTAIRE ───
  {
    id: 1,
    name: "Riz Parfumé 25kg - Premium",
    image: IMAGES.riceBags,
    price: 14800,
    moq: 10,
    unit: "sacs",
    seller: "Ets Ahouandjinou",
    rating: 4.8,
    category: "Alimentaire",
    inStock: true,
    paliers: [
      { qty: 10, price: 14800 },
      { qty: 50, price: 13500 },
      { qty: 100, price: 12800 },
    ],
  },
  {
    id: 2,
    name: "Huile de palme raffinée 20L",
    image: IMAGES.palmOil,
    price: 17600,
    moq: 5,
    unit: "bidons",
    seller: "Soja Gold Bénin",
    rating: 4.6,
    category: "Alimentaire",
    inStock: true,
    paliers: [
      { qty: 5, price: 17600 },
      { qty: 20, price: 16500 },
      { qty: 50, price: 15800 },
    ],
  },
  {
    id: 9,
    name: "Riz Basmati 50kg Inde",
    image: IMAGES.grocery,
    price: 32000,
    moq: 5,
    unit: "sacs",
    seller: "Import Céréales Plus",
    rating: 4.7,
    category: "Alimentaire",
    inStock: true,
    paliers: [
      { qty: 5, price: 32000 },
      { qty: 20, price: 29500 },
      { qty: 50, price: 27000 },
    ],
  },
  {
    id: 10,
    name: "Concentré de tomate 400g x48",
    image: IMAGES.tomatoPaste,
    price: 22500,
    moq: 10,
    unit: "cartons",
    seller: "Ets Ahouandjinou",
    rating: 4.5,
    category: "Alimentaire",
    inStock: true,
    paliers: [
      { qty: 10, price: 22500 },
      { qty: 30, price: 20800 },
      { qty: 100, price: 19000 },
    ],
  },
  {
    id: 11,
    name: "Farine de blé T55 - 50kg",
    image: IMAGES.flour,
    price: 19500,
    moq: 10,
    unit: "sacs",
    seller: "MoulinsAfric",
    rating: 4.4,
    category: "Alimentaire",
    inStock: true,
    paliers: [
      { qty: 10, price: 19500 },
      { qty: 50, price: 18000 },
      { qty: 100, price: 16800 },
    ],
  },
  {
    id: 12,
    name: "Sucre en poudre 50kg",
    image: IMAGES.sugar,
    price: 26000,
    moq: 5,
    unit: "sacs",
    seller: "SucreBénin SA",
    rating: 4.3,
    category: "Alimentaire",
    inStock: false,
    paliers: [
      { qty: 5, price: 26000 },
      { qty: 20, price: 24500 },
      { qty: 50, price: 23000 },
    ],
  },
  {
    id: 13,
    name: "Lait en poudre 400g x24",
    image: IMAGES.milkPowder,
    price: 48000,
    moq: 5,
    unit: "cartons",
    seller: "DairyGros Afrique",
    rating: 4.6,
    category: "Alimentaire",
    inStock: true,
    paliers: [
      { qty: 5, price: 48000 },
      { qty: 15, price: 45000 },
      { qty: 30, price: 42000 },
    ],
  },
  {
    id: 14,
    name: "Pâtes alimentaires 500g x30",
    image: IMAGES.pasta,
    price: 15000,
    moq: 10,
    unit: "cartons",
    seller: "Ets Ahouandjinou",
    rating: 4.2,
    category: "Alimentaire",
    inStock: true,
    paliers: [
      { qty: 10, price: 15000 },
      { qty: 30, price: 13800 },
      { qty: 100, price: 12500 },
    ],
  },
  // ─── BOISSONS ───
  {
    id: 15,
    name: "Eau minérale 1.5L x12",
    image: IMAGES.mineralWater,
    price: 3500,
    moq: 50,
    unit: "packs",
    seller: "Boissons du Golfe",
    rating: 4.5,
    category: "Boissons",
    inStock: true,
    paliers: [
      { qty: 50, price: 3500 },
      { qty: 100, price: 3200 },
      { qty: 500, price: 2900 },
    ],
  },
  {
    id: 16,
    name: "Jus de fruits Tropicaux 33cl x24",
    image: IMAGES.juices,
    price: 8500,
    moq: 20,
    unit: "cartons",
    seller: "JusNatura Bénin",
    rating: 4.4,
    category: "Boissons",
    inStock: true,
    paliers: [
      { qty: 20, price: 8500 },
      { qty: 50, price: 7800 },
      { qty: 100, price: 7200 },
    ],
  },
  {
    id: 17,
    name: "Sodabi traditionnel 1L x12",
    image: IMAGES.sodabi,
    price: 18000,
    moq: 10,
    unit: "cartons",
    seller: "Distillerie Savalou",
    rating: 4.1,
    category: "Boissons",
    inStock: true,
    paliers: [
      { qty: 10, price: 18000 },
      { qty: 30, price: 16500 },
      { qty: 50, price: 15200 },
    ],
  },
  {
    id: 18,
    name: "Bissap concentré 5L",
    image: IMAGES.bissap,
    price: 4500,
    moq: 20,
    unit: "bidons",
    seller: "Saveurs d'Afrique",
    rating: 4.7,
    category: "Boissons",
    inStock: true,
    paliers: [
      { qty: 20, price: 4500 },
      { qty: 50, price: 4000 },
      { qty: 100, price: 3600 },
    ],
  },
  {
    id: 19,
    name: "Thé vert sachets x100 boîtes",
    image: IMAGES.greenTea,
    price: 12000,
    moq: 10,
    unit: "boîtes",
    seller: "Import Thé Bénin",
    rating: 4.3,
    category: "Boissons",
    inStock: false,
    paliers: [
      { qty: 10, price: 12000 },
      { qty: 30, price: 11000 },
      { qty: 50, price: 10000 },
    ],
  },
  // ─── MAISON ET JARDIN ───
  {
    id: 3,
    name: "Savon de ménage - Carton 48pcs",
    image: IMAGES.hygiene,
    price: 9000,
    moq: 20,
    unit: "cartons",
    seller: "ProClean SARL",
    rating: 4.5,
    category: "Maison",
    inStock: true,
    paliers: [
      { qty: 20, price: 9000 },
      { qty: 50, price: 8200 },
      { qty: 100, price: 7500 },
    ],
  },
  {
    id: 8,
    name: "Détergent liquide 5L - Lot 12",
    image: IMAGES.soapBulk,
    price: 18000,
    moq: 10,
    unit: "lots",
    seller: "ProClean SARL",
    rating: 4.5,
    category: "Maison",
    inStock: false,
    paliers: [
      { qty: 10, price: 18000 },
      { qty: 30, price: 16500 },
      { qty: 50, price: 15000 },
    ],
  },
  {
    id: 20,
    name: "Papier toilette 2 plis x96 rouleaux",
    image: IMAGES.toiletPaper,
    price: 14500,
    moq: 10,
    unit: "packs",
    seller: "HygiènePlus",
    rating: 4.6,
    category: "Maison",
    inStock: true,
    paliers: [
      { qty: 10, price: 14500 },
      { qty: 30, price: 13200 },
      { qty: 50, price: 12000 },
    ],
  },
  {
    id: 21,
    name: "Eau de javel 5L x6",
    image: IMAGES.bleach,
    price: 7200,
    moq: 20,
    unit: "packs",
    seller: "ProClean SARL",
    rating: 4.3,
    category: "Maison",
    inStock: true,
    paliers: [
      { qty: 20, price: 7200 },
      { qty: 50, price: 6500 },
      { qty: 100, price: 5900 },
    ],
  },
  {
    id: 22,
    name: "Dentifrice 100ml x48",
    image: IMAGES.toothpaste,
    price: 24000,
    moq: 5,
    unit: "cartons",
    seller: "HygiènePlus",
    rating: 4.4,
    category: "Maison",
    inStock: true,
    paliers: [
      { qty: 5, price: 24000 },
      { qty: 15, price: 22000 },
      { qty: 30, price: 20500 },
    ],
  },
  {
    id: 23,
    name: "Serpillière microfibre x50",
    image: IMAGES.mopCleaning,
    price: 35000,
    moq: 5,
    unit: "lots",
    seller: "ProClean SARL",
    rating: 4.2,
    category: "Maison",
    inStock: true,
    paliers: [
      { qty: 5, price: 35000 },
      { qty: 10, price: 32000 },
      { qty: 20, price: 29000 },
    ],
  },
  // ─── BEAUTÉ ET SOINS PERSONNELS ───
  {
    id: 5,
    name: "Crème corporelle 500ml - Lot 24",
    image: IMAGES.cosmetics,
    price: 36000,
    moq: 5,
    unit: "lots",
    seller: "Beauty Queen",
    rating: 4.4,
    category: "Beauté",
    inStock: true,
    paliers: [
      { qty: 5, price: 36000 },
      { qty: 15, price: 33000 },
      { qty: 30, price: 30000 },
    ],
  },
  {
    id: 24,
    name: "Huile de coco vierge 500ml x24",
    image: IMAGES.coconutOil,
    price: 28000,
    moq: 10,
    unit: "cartons",
    seller: "NaturaBeauté",
    rating: 4.8,
    category: "Beauté",
    inStock: true,
    paliers: [
      { qty: 10, price: 28000 },
      { qty: 25, price: 25500 },
      { qty: 50, price: 23000 },
    ],
  },
  {
    id: 25,
    name: "Beurre de karité brut 10kg",
    image: IMAGES.sheaButter,
    price: 22000,
    moq: 5,
    unit: "seaux",
    seller: "Karité Gold",
    rating: 4.9,
    category: "Beauté",
    inStock: true,
    paliers: [
      { qty: 5, price: 22000 },
      { qty: 15, price: 20000 },
      { qty: 30, price: 18500 },
    ],
  },
  {
    id: 26,
    name: "Mèches brésiliennes 20\" x10",
    image: IMAGES.hairExtensions,
    price: 85000,
    moq: 3,
    unit: "lots",
    seller: "Beauty Queen",
    rating: 4.6,
    category: "Beauté",
    inStock: true,
    paliers: [
      { qty: 3, price: 85000 },
      { qty: 10, price: 78000 },
      { qty: 20, price: 72000 },
    ],
  },
  {
    id: 27,
    name: "Savon noir africain 200g x50",
    image: IMAGES.blackSoap,
    price: 18500,
    moq: 10,
    unit: "lots",
    seller: "NaturaBeauté",
    rating: 4.7,
    category: "Beauté",
    inStock: false,
    paliers: [
      { qty: 10, price: 18500 },
      { qty: 25, price: 16800 },
      { qty: 50, price: 15200 },
    ],
  },
  {
    id: 28,
    name: "Vernis à ongles x120 couleurs",
    image: IMAGES.nailPolish,
    price: 42000,
    moq: 3,
    unit: "lots",
    seller: "Beauty Queen",
    rating: 4.3,
    category: "Beauté",
    inStock: true,
    paliers: [
      { qty: 3, price: 42000 },
      { qty: 10, price: 38000 },
      { qty: 20, price: 35000 },
    ],
  },
  // ─── MODE ET ACCESSOIRES ───
  {
    id: 4,
    name: "Tissu Wax Hollandais 12 yards",
    image: IMAGES.textile,
    price: 28000,
    moq: 10,
    unit: "pièces",
    seller: "Tokpa Textiles",
    rating: 4.9,
    category: "Textile",
    inStock: true,
    paliers: [
      { qty: 10, price: 28000 },
      { qty: 30, price: 25000 },
      { qty: 100, price: 22000 },
    ],
  },
  {
    id: 29,
    name: "Bazin riche 10 yards",
    image: IMAGES.textile,
    price: 45000,
    moq: 5,
    unit: "pièces",
    seller: "Missèbo Fashion",
    rating: 4.8,
    category: "Textile",
    inStock: true,
    paliers: [
      { qty: 5, price: 45000 },
      { qty: 15, price: 42000 },
      { qty: 30, price: 39000 },
    ],
  },
  {
    id: 30,
    name: "T-shirts blancs coton x50",
    image: IMAGES.whiteTshirts,
    price: 75000,
    moq: 3,
    unit: "lots",
    seller: "Textisud Bénin",
    rating: 4.4,
    category: "Textile",
    inStock: true,
    paliers: [
      { qty: 3, price: 75000 },
      { qty: 10, price: 68000 },
      { qty: 20, price: 62000 },
    ],
  },
  {
    id: 31,
    name: "Pagne Kente 6 yards",
    image: IMAGES.kente,
    price: 35000,
    moq: 10,
    unit: "pièces",
    seller: "Tokpa Textiles",
    rating: 4.7,
    category: "Textile",
    inStock: true,
    paliers: [
      { qty: 10, price: 35000 },
      { qty: 25, price: 32000 },
      { qty: 50, price: 29000 },
    ],
  },
  {
    id: 32,
    name: "Draps de lit 2 places x10",
    image: IMAGES.bedSheets,
    price: 55000,
    moq: 5,
    unit: "lots",
    seller: "Missèbo Fashion",
    rating: 4.5,
    category: "Textile",
    inStock: false,
    paliers: [
      { qty: 5, price: 55000 },
      { qty: 10, price: 50000 },
      { qty: 20, price: 46000 },
    ],
  },
  {
    id: 33,
    name: "Friperie balles 100kg",
    image: IMAGES.usedClothes,
    price: 125000,
    moq: 1,
    unit: "balles",
    seller: "FripeKing Cotonou",
    rating: 4.2,
    category: "Textile",
    inStock: true,
    paliers: [
      { qty: 1, price: 125000 },
      { qty: 5, price: 115000 },
      { qty: 10, price: 105000 },
    ],
  },
  // ─── ÉLECTRONIQUE GRAND PUBLIC ───
  {
    id: 6,
    name: "Câble USB-C - Pack 50pcs",
    image: IMAGES.electronics,
    price: 25000,
    moq: 10,
    unit: "packs",
    seller: "TechGros Bénin",
    rating: 4.7,
    category: "Électronique",
    inStock: true,
    paliers: [
      { qty: 10, price: 25000 },
      { qty: 30, price: 22000 },
      { qty: 100, price: 19000 },
    ],
  },
  {
    id: 34,
    name: "Écouteurs Bluetooth x20",
    image: IMAGES.earbuds,
    price: 48000,
    moq: 5,
    unit: "lots",
    seller: "TechGros Bénin",
    rating: 4.5,
    category: "Électronique",
    inStock: true,
    paliers: [
      { qty: 5, price: 48000 },
      { qty: 15, price: 44000 },
      { qty: 30, price: 40000 },
    ],
  },
  {
    id: 35,
    name: "Coques smartphone assorties x100",
    image: IMAGES.phoneCases,
    price: 35000,
    moq: 5,
    unit: "lots",
    seller: "MobiAccessoires",
    rating: 4.3,
    category: "Électronique",
    inStock: true,
    paliers: [
      { qty: 5, price: 35000 },
      { qty: 15, price: 31000 },
      { qty: 30, price: 28000 },
    ],
  },
  {
    id: 36,
    name: "Chargeur rapide 20W x50",
    image: IMAGES.fastCharger,
    price: 62000,
    moq: 5,
    unit: "lots",
    seller: "TechGros Bénin",
    rating: 4.6,
    category: "Électronique",
    inStock: true,
    paliers: [
      { qty: 5, price: 62000 },
      { qty: 10, price: 57000 },
      { qty: 20, price: 52000 },
    ],
  },
  {
    id: 37,
    name: "Ampoules LED 12W x100",
    image: IMAGES.ledBulbs,
    price: 28000,
    moq: 10,
    unit: "lots",
    seller: "ElectroPlus",
    rating: 4.4,
    category: "Électronique",
    inStock: true,
    paliers: [
      { qty: 10, price: 28000 },
      { qty: 25, price: 25500 },
      { qty: 50, price: 23000 },
    ],
  },
  {
    id: 38,
    name: "Power Bank 10000mAh x20",
    image: IMAGES.powerBank,
    price: 55000,
    moq: 5,
    unit: "lots",
    seller: "TechGros Bénin",
    rating: 4.5,
    category: "Électronique",
    inStock: false,
    paliers: [
      { qty: 5, price: 55000 },
      { qty: 10, price: 50000 },
      { qty: 20, price: 46000 },
    ],
  },
  // ─── CONSTRUCTION ET MATÉRIAUX ───
  {
    id: 39,
    name: "Ciment CPA 50kg",
    image: IMAGES.cement,
    price: 5200,
    moq: 50,
    unit: "sacs",
    seller: "MatBTP Bénin",
    rating: 4.6,
    category: "BTP",
    inStock: true,
    paliers: [
      { qty: 50, price: 5200 },
      { qty: 200, price: 4900 },
      { qty: 500, price: 4600 },
    ],
  },
  {
    id: 40,
    name: "Fer à béton 12mm - barre 12m",
    image: IMAGES.ironBars,
    price: 4800,
    moq: 50,
    unit: "barres",
    seller: "FerroConstruct",
    rating: 4.5,
    category: "BTP",
    inStock: true,
    paliers: [
      { qty: 50, price: 4800 },
      { qty: 100, price: 4500 },
      { qty: 500, price: 4200 },
    ],
  },
  {
    id: 41,
    name: "Peinture murale 20L - Blanc",
    image: IMAGES.paint,
    price: 18000,
    moq: 10,
    unit: "seaux",
    seller: "PeintureExpress",
    rating: 4.3,
    category: "BTP",
    inStock: true,
    paliers: [
      { qty: 10, price: 18000 },
      { qty: 25, price: 16500 },
      { qty: 50, price: 15200 },
    ],
  },
  {
    id: 42,
    name: "Tôle bac alu 3m x6",
    image: IMAGES.roofSheets,
    price: 8500,
    moq: 20,
    unit: "tôles",
    seller: "MatBTP Bénin",
    rating: 4.4,
    category: "BTP",
    inStock: true,
    paliers: [
      { qty: 20, price: 8500 },
      { qty: 50, price: 7800 },
      { qty: 100, price: 7200 },
    ],
  },
  {
    id: 43,
    name: "Carreaux 40x40cm x50 m²",
    image: IMAGES.tiles,
    price: 125000,
    moq: 2,
    unit: "palettes",
    seller: "FerroConstruct",
    rating: 4.2,
    category: "BTP",
    inStock: false,
    paliers: [
      { qty: 2, price: 125000 },
      { qty: 5, price: 118000 },
      { qty: 10, price: 110000 },
    ],
  },
  // ─── ALIMENTAIRE (Vivrier) ───
  {
    id: 7,
    name: "Maïs séché 50kg",
    image: IMAGES.driedCorn,
    price: 8500,
    moq: 20,
    unit: "sacs",
    seller: "AgroNord",
    rating: 4.3,
    category: "Alimentaire",
    inStock: true,
    paliers: [
      { qty: 20, price: 8500 },
      { qty: 50, price: 7800 },
      { qty: 200, price: 7200 },
    ],
  },
  {
    id: 44,
    name: "Igname pilée 25kg",
    image: IMAGES.tubers,
    price: 12000,
    moq: 10,
    unit: "sacs",
    seller: "Vivriers du Nord",
    rating: 4.5,
    category: "Alimentaire",
    inStock: true,
    paliers: [
      { qty: 10, price: 12000 },
      { qty: 30, price: 11000 },
      { qty: 50, price: 10200 },
    ],
  },
  {
    id: 45,
    name: "Manioc séché (gari) 50kg",
    image: IMAGES.vegetables,
    price: 7500,
    moq: 20,
    unit: "sacs",
    seller: "AgroNord",
    rating: 4.6,
    category: "Alimentaire",
    inStock: true,
    paliers: [
      { qty: 20, price: 7500 },
      { qty: 50, price: 6800 },
      { qty: 100, price: 6200 },
    ],
  },
  {
    id: 46,
    name: "Haricots rouges 25kg",
    image: IMAGES.redBeans,
    price: 15500,
    moq: 10,
    unit: "sacs",
    seller: "Vivriers du Nord",
    rating: 4.4,
    category: "Alimentaire",
    inStock: true,
    paliers: [
      { qty: 10, price: 15500 },
      { qty: 30, price: 14200 },
      { qty: 50, price: 13000 },
    ],
  },
  {
    id: 47,
    name: "Arachide décortiquée 50kg",
    image: IMAGES.peanuts,
    price: 22000,
    moq: 5,
    unit: "sacs",
    seller: "AgroNord",
    rating: 4.3,
    category: "Alimentaire",
    inStock: true,
    paliers: [
      { qty: 5, price: 22000 },
      { qty: 20, price: 20000 },
      { qty: 50, price: 18500 },
    ],
  },
  {
    id: 48,
    name: "Soja grain 50kg",
    image: IMAGES.soybeans,
    price: 18000,
    moq: 10,
    unit: "sacs",
    seller: "Soja Gold Bénin",
    rating: 4.5,
    category: "Alimentaire",
    inStock: false,
    paliers: [
      { qty: 10, price: 18000 },
      { qty: 30, price: 16500 },
      { qty: 50, price: 15200 },
    ],
  },
  // ─── MACHINES INDUSTRIELLES ───
  {
    id: 49,
    name: "Groupe électrogène 5kVA",
    image: IMAGES.generator,
    price: 385000,
    moq: 1,
    unit: "unités",
    seller: "EquipPro Bénin",
    rating: 4.7,
    category: "Industriel",
    inStock: true,
    paliers: [
      { qty: 1, price: 385000 },
      { qty: 3, price: 365000 },
      { qty: 5, price: 345000 },
    ],
  },
  {
    id: 50,
    name: "Congélateur commercial 500L",
    image: IMAGES.refrigerator,
    price: 295000,
    moq: 1,
    unit: "unités",
    seller: "FroidAfric SARL",
    rating: 4.6,
    category: "Maison",
    inStock: true,
    paliers: [
      { qty: 1, price: 295000 },
      { qty: 3, price: 278000 },
      { qty: 5, price: 260000 },
    ],
  },
  {
    id: 51,
    name: "Machine à coudre industrielle",
    image: IMAGES.sewingMachine,
    price: 180000,
    moq: 1,
    unit: "unités",
    seller: "CoutureEquip Cotonou",
    rating: 4.8,
    category: "Industriel",
    inStock: true,
    paliers: [
      { qty: 1, price: 180000 },
      { qty: 3, price: 168000 },
      { qty: 5, price: 155000 },
    ],
  },
  {
    id: 52,
    name: "Moulin à grains électrique",
    image: IMAGES.millingMachine,
    price: 425000,
    moq: 1,
    unit: "unités",
    seller: "AgroMachines Bénin",
    rating: 4.5,
    category: "Industriel",
    inStock: true,
    paliers: [
      { qty: 1, price: 425000 },
      { qty: 2, price: 405000 },
      { qty: 3, price: 385000 },
    ],
  },
  {
    id: 53,
    name: "Poste à souder inverseur 200A",
    image: IMAGES.weldingMachine,
    price: 75000,
    moq: 1,
    unit: "unités",
    seller: "BricoPlus Bénin",
    rating: 4.4,
    category: "Industriel",
    inStock: true,
    paliers: [
      { qty: 1, price: 75000 },
      { qty: 5, price: 68000 },
      { qty: 10, price: 62000 },
    ],
  },
  {
    id: 54,
    name: "Pompe à eau submersible 2HP",
    image: IMAGES.waterPump,
    price: 125000,
    moq: 1,
    unit: "unités",
    seller: "HydroEquip Bénin",
    rating: 4.3,
    category: "Industriel",
    inStock: true,
    paliers: [
      { qty: 1, price: 125000 },
      { qty: 3, price: 115000 },
      { qty: 5, price: 105000 },
    ],
  },
];
